= Oracle Struct Metadata Code Generator

== Introducción

Esta libreróa permite la generación de código utilizado para la invocación de procedimientos
almacenados de Oracle a través de la librería
https://github.com/labcabrera/osm-connector[osm-connector].

La librería consultará la meta-información de Oracle y generará los tipos y las interfaces
necesarias para la invocación de un determinado procedimiento almacenado.

== Utilización

Para generar el código deberemos tener conectividad a la base de datos de Oracle.

Después simplemente tendremos que invocar a la clase `CodeGenerator` pasando la información de
nuestro procedimiento almacenado utilizando la clase `CodeGenerationRequest` con la siguiente
estructura:

[source,json]
----
{
  "jdbcUrl" : "jdbc:oracle:thin:@some-host:1521:schema",
  "user" : "DB_USER",
  "password" : "DB_PASSWORD",
  "objectName" : "MY_OBJET_NAME",
  "procedureName" : "SOME_PROCEDURE",
  "options" : {
    "entityPackage" : "org.lab.samples.osm.participant.model",
    "entityBaseFolder" : "./src/test/java",
    "executorPackage" : "org.lab.samples.osm.participant.executor",
    "executorBaseFolder" : "./src/test/java",
    "cleanTargetFolders" : false
  }
}
----

== Sobrecarga de procedimientos

Dado que en Oracle es posible tener varios procedimientos con el mismo nombre podemos utilizar la opcion _overload_ del
objeto `CodeGenerationOptions` para discrimiar entre los diferentes procedimientos.

== Pruebas locales

Para hacer las pruebas podemos utilizar la imagen Docker
https://hub.docker.com/r/wnameless/oracle-xe-11g/[wnameless/oracle-xe-11g]
de Oracle Database Express Edition 11g.

Para ejecutar la imagen simplemente ejecutaremos:

----
docker run -d -p 49161:1521 -e ORACLE_ALLOW_REMOTE=true wnameless/oracle-xe-11g
----


