-- DROP USER OSM CASCADE;

CREATE USER OSM IDENTIFIED BY OSM;

ALTER USER OSM quota 256m on SYSTEM;

ALTER SESSION SET CURRENT_SCHEMA = OSM;

CREATE TABLE OSM.CUSTOMER (
	ID NUMBER(10) NOT NULL,
	FIRST_NAME VARCHAR2(32) NOT NULL,
	LAST_NAME VARCHAR2(32) NOT NULL,
	CODE VARCHAR2(64) NOT NULL,
	CREATED TIMESTAMP,
	EXPIRATION DATE,
	ACTIVE NUMBER(1)
);

CREATE OR REPLACE TYPE OSM.CUSTOMER_TYPE
AS OBJECT (
	ID NUMBER(10) NOT NULL,
	FIRST_NAME VARCHAR2(32) NOT NULL,
	LAST_NAME VARCHAR2(32) NOT NULL,
	CODE VARCHAR2(64) NOT NULL,
	CREATED TIMESTAMP,
	EXPIRATION DATE,
	ACTIVE NUMBER(1)
);

CREATE OR REPLACE TYPE OSM.CUSTOMER_TAB_TYPE AS TABLE OF CUSTOMER_TYPE;

CREATE OR REPLACE TYPE OSM.CUSTOMER_ARR_TYPE AS VARRAY(20) OF CUSTOMER_TYPE;

CREATE OR REPLACE PACKAGE OSM_TEST AS PROCEDURE SP_OSM_BASIC_ADD;


/*

TODO package initialization dont work

CREATE OR REPLACE PACKAGE BODY OSM.OSM_TEST
AS

	PROCEDURE SP_OSM_BASIC_ADD (
		in_01 IN NUMBER,
		in_02 IN NUMBER,
		out_01 OUT NUMBER)
	IS
	BEGIN	
		out_01 := in_01 + in_02;
	END;

	PROCEDURE CUSTOMER_ADD (customer_in IN CUSTOMER_TYPE) AS
	BEGIN
		INSERT INTO CUSTOMER (
			ID,
			FIRST_NAME,
			LAST_NAME,
			CODE,
			CREATED,
			EXPIRATION)
		VALUES (
			customer_in.ID,
			customer_in.FIRST_NAME,
			customer_in.LAST_NAME,
			customer_in.CODE
			customer_in.CREATED,
			customer_in.EXPIRATION);
	END;

END;
*/
